set -g default-terminal "screen-256color"

set -g base-index 1
set -g status-position top
set -g status-style "bg=green, fg=colour255"
set -g message-style "bg=yellow, fg=colour255"

set -g mouse on
set -g mode-keys vi
set -g status-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h resize-pane -L 5
bind C-j resize-pane -D 5
bind C-k resize-pane -U 5
bind C-l resize-pane -R 5

bind a split-window -h -p 25 "claude"

bind -n C-S-h previous-window
bind -n C-S-l next-window

# Start selection with 'v' (Visual Mode)
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Copy with 'y' (Yank)
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g window-status-current-style 'bg=colour231,fg=green,bold'
set -g window-status-style 'bg=green,fg=colour231'

set -g window-style 'bg=colour254'
set -g window-active-style 'bg=colour231'
