set -g default-terminal "screen-256color"

set -g base-index 1
set -g status-position top
set -g status-style "bg=green, fg=colour255"

set -g mode-keys vi
set -g status-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h resize-pane -L 5
bind C-j resize-pane -D 5
bind C-k resize-pane -U 5
bind C-l resize-pane -R 5

bind a split-window -h -p 25 "claude"
