[tools]
lua = "latest"
node = "24"
go = "latest"
deno = "latest"
bun = "latest"
"npm:httpyac" = "latest"
"npm:vercel" = "latest"
lazygit = "latest"
lazydocker = "latest"
bitwarden = "latest"
zoxide = "latest"
bat = "latest"
"cargo:eza" = "latest"
"cargo:tlrc" = "latest"
"npm:@botpress/cli" = "latest"
"npm:ts-node" = "latest"
"npm:typescript" = "latest"
"npm:ngrok" = "latest"
neovim = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"npm:typescript-language-server" = "latest"
tmux = "latest"
opencode = "latest"
yazi = "latest"
"npm:oxfmt" = "latest"
"npm:@prisma/language-server" = "latest"
difftastic = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
