[tools]
lua = "latest"
node = "24"
go = "latest"
deno = "latest"
bun = "latest"
"npm:vercel" = "latest"
lazygit = "latest"
lazydocker = "latest"
bitwarden = "latest"
zoxide = "latest"
bat = "latest"
"cargo:tlrc" = "latest"
"npm:@botpress/cli" = "latest"
"npm:ts-node" = "latest"
"npm:typescript" = "latest"
neovim = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"npm:typescript-language-server" = "latest"
yazi = "latest"
"npm:oxfmt" = "latest"
"npm:@prisma/language-server" = "latest"
difftastic = "latest"
infisical = "latest"
herdr = "latest"
starship = "latest"
eza = "latest"
"github:earendil-works/pi" = "latest"
rg = "latest"
fd = "latest"
usage = "latest"
rust-analyzer = "latest"
gh = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
